#!/usr/bin/python3


import os
import glob
import pathlib
import ninja

build_file = open("build.ninja", "w+")

ninja = ninja.Writer(output=build_file)

ninja.variable("cflags", "-Wall -Iinclude/  -march=native -DOAK_STANDALONE_HOOKS -Ofast")
ninja.variable("cxxflags", "-Wall -Iinclude/  -march=native -DOAK_STANDALONE_HOOKS -DOAK_PROFILE_DRAW_SYNC -Ofast")
ninja.variable("ldflags", "-L./libs -lglfw3 -lm")

ninja.rule("cc", "gcc $cflags -c $in -o $out")
ninja.rule("cxx", "g++ $cxxflags -c $in -o $out")
ninja.rule("link", "g++ $in -o $out $ldflags")
ninja.rule("ar", "ar rcs $out $in")

to_obj_path = lambda p: pathlib.Path(*pathlib.Path(p).parts[1:])

c_sources = list(glob.iglob("src/**/*.c", recursive=True))

objs = []

print(f"Found {len(c_sources)} C Sources")
for source in c_sources:
    print(f"- {source}")
    ninja.build(f"obj/{to_obj_path(source)}.o", "cc", inputs=source)
    objs.append(f"obj/{to_obj_path(source)}.o")

cxx_sources = list(glob.iglob("src/**/*.cpp", recursive=True))

print(f"Found {len(cxx_sources)} Cpp Sources")
for source in cxx_sources:
    print(f"- {source}")
    ninja.build(f"obj/{to_obj_path(source)}.o", "cxx", inputs=source)
    objs.append(f"obj/{to_obj_path(source)}.o")

ninja.build("bin/oak", "link", objs)
ninja.build("bin/liboak.a", "ar", objs)



build_file.close()

